// Package view provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package view

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AgreementType.
const (
	Cookie         AgreementType = "cookie"
	LoyaltyProgram AgreementType = "loyaltyProgram"
	PersonalData   AgreementType = "personalData"
	Subscription   AgreementType = "subscription"
	TermsOfUse     AgreementType = "termsOfUse"
)

// Agreement defines model for Agreement.
type Agreement struct {
	ConfirmedAt time.Time     `json:"confirmedAt"`
	Type        AgreementType `json:"type"`
}

// AgreementType defines model for Agreement.Type.
type AgreementType string

// AuthAnonymousShort defines model for AuthAnonymousShort.
type AuthAnonymousShort struct {
	Agreements *[]Agreement `json:"agreements"`

	// Группа пользователя anonymous/authorized
	Group string `json:"group"`

	// Имя пользователя - если пользователь не анонимный, если анонимный пустая строка
	Name string `json:"name"`
}

// AuthCity defines model for AuthCity.
type AuthCity struct {
	Id    int    `json:"id"`
	Title string `json:"title"`
}

// AuthToken defines model for AuthToken.
type AuthToken struct {
	AccessToken     string  `json:"accessToken"`
	ExpAccessToken  float32 `json:"expAccessToken"`
	ExpRefreshToken float32 `json:"expRefreshToken"`
	RefreshToken    string  `json:"refreshToken"`
}

// Простая ошибка
type ErrorResponseWithMessage struct {
	// Текст ошибки
	Message *string `json:"message,omitempty"`

	// ID запроса
	RequestId *string `json:"requestId,omitempty"`
}

// Login defines model for Login.
type Login struct {
	City  AuthCity           `json:"city"`
	Token AuthToken          `json:"token"`
	User  AuthAnonymousShort `json:"user"`
}

// RefreshToken defines model for RefreshToken.
type RefreshToken = string

// Простая ошибка
type BadRequest = ErrorResponseWithMessage

// PostAuthResponse defines model for PostAuthResponse.
type PostAuthResponse = Login

// PostRegistrationResponse defines model for PostRegistrationResponse.
type PostRegistrationResponse = Login

// PutLogoutResponse defines model for PutLogoutResponse.
type PutLogoutResponse struct {
	Data AuthToken `json:"data"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	RefreshToken RefreshToken `form:"refreshToken" json:"refreshToken"`
}
