// Package view provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package view

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AuthToken defines model for AuthToken.
type AuthToken = map[string]interface{}

// Простая ошибка
type ErrorResponseWithMessage struct {
	// Текст ошибки
	Message *string `json:"message,omitempty"`

	// ID запроса
	RequestId *string `json:"requestId,omitempty"`
}

// Login defines model for Login.
type Login struct {
	Token AuthToken `json:"token"`
}

// OK
type RegistrationResult struct {
	Data RegistrationResultData `json:"data"`
}

// RegistrationResultData defines model for RegistrationResultData.
type RegistrationResultData struct {
	Result bool `json:"result"`
}

// Тело запроса
type RequestBody struct {
	// Логин пользователя
	Login string `json:"login"`

	// Пароль пользователя
	Password string `json:"password"`
}

// Тело ошибки
type SimpleErrorBody struct {
	// Описание ошибки
	Data struct {
		// Текст ошибки
		Error string `json:"error"`
	} `json:"data"`
}

// RefreshToken defines model for RefreshToken.
type RefreshToken = string

// Простая ошибка
type BadRequest = ErrorResponseWithMessage

// PostAuthResponse defines model for PostAuthResponse.
type PostAuthResponse = Login

// OK
type PostRegistrationResponse = RegistrationResult

// PutLogoutResponse defines model for PutLogoutResponse.
type PutLogoutResponse struct {
	Data AuthToken `json:"data"`
}

// SimpleErrorResponse defines model for SimpleErrorResponse.
type SimpleErrorResponse struct {
	// Описание ошибки
	Data struct {
		// Текст ошибки
		Error string `json:"error"`
	} `json:"data"`
}

// Тело запроса
type PostRegistrationRequestData = RequestBody

// PutLogoutParams defines parameters for PutLogout.
type PutLogoutParams struct {
	RefreshToken RefreshToken `form:"refreshToken" json:"refreshToken"`
}

// RegistrationRequestDataJSONRequestBody defines body for RegistrationRequestData for application/json ContentType.
type RegistrationRequestDataJSONRequestBody = PostRegistrationRequestData
