openapi: 3.0.3
info:
  title: Nofelet web service
  description: Методы V1
  version: 2.0.0
servers:
  - url: https://maximtretjakov.github.io/nofelet-ui/
    description: dev env
paths:
  # Регистрация пользователя
  /api/v1/registration:
    $ref: 'routes/Registration.yaml#/paths/RegistrationRequestData'

  # Авторизация
  /api/v1/auth:
    $ref: "routes/Auth.yaml#/paths/Auth"
  /api/v1/logout:
    $ref: "routes/Logout.yaml#/paths/Logout"
